import { JsonPipe } from '@angular/common';
import { Component, computed, signal } from '@angular/core';
import { FormControl, ReactiveFormsModule, Validators } from '@angular/forms';
import {
  TaxIdValidationResult,
  normalizeTaxId,
  validateTaxId,
} from 'tax-id';
import { taxIdValidator } from 'tax-id/angular';

interface TestCase {
  readonly label: string;
  readonly country: string;
  readonly value: string;
  readonly expectation: string;
}

@Component({
  selector: 'app-root',
  imports: [JsonPipe, ReactiveFormsModule],
  templateUrl: './app.html',
  styleUrl: './app.css',
})
export class App {
  protected readonly countries = [
    { code: 'AD', label: 'Andorra' },
    { code: 'AL', label: 'Albania' },
    { code: 'AT', label: 'Austria' },
    { code: 'BA', label: 'Bosnia ed Erzegovina' },
    { code: 'BE', label: 'Belgio' },
    { code: 'BG', label: 'Bulgaria' },
    { code: 'CH', label: 'Svizzera' },
    { code: 'CY', label: 'Cipro' },
    { code: 'CZ', label: 'Cechia' },
    { code: 'DK', label: 'Danimarca' },
    { code: 'DE', label: 'Germania' },
    { code: 'EE', label: 'Estonia' },
    { code: 'IT', label: 'Italia' },
    { code: 'ES', label: 'Spagna' },
    { code: 'FI', label: 'Finlandia' },
    { code: 'FR', label: 'Francia' },
    { code: 'GR', label: 'Grecia' },
    { code: 'HR', label: 'Croazia' },
    { code: 'HU', label: 'Ungheria' },
    { code: 'IS', label: 'Islanda' },
    { code: 'IE', label: 'Irlanda' },
    { code: 'LV', label: 'Lettonia' },
    { code: 'LI', label: 'Liechtenstein' },
    { code: 'LT', label: 'Lituania' },
    { code: 'LU', label: 'Lussemburgo' },
    { code: 'MD', label: 'Moldova' },
    { code: 'ME', label: 'Montenegro' },
    { code: 'MK', label: 'Macedonia del Nord' },
    { code: 'MT', label: 'Malta' },
    { code: 'NL', label: 'Paesi Bassi' },
    { code: 'NO', label: 'Norvegia' },
    { code: 'PL', label: 'Polonia' },
    { code: 'PT', label: 'Portogallo' },
    { code: 'RO', label: 'Romania' },
    { code: 'RS', label: 'Serbia' },
    { code: 'SE', label: 'Svezia' },
    { code: 'SI', label: 'Slovenia' },
    { code: 'SK', label: 'Slovacchia' },
    { code: 'TR', label: 'Turchia' },
    { code: 'UA', label: 'Ucraina' },
    { code: 'BY', label: 'Bielorussia' },
    { code: 'GB', label: 'Regno Unito' },
    { code: 'MC', label: 'Monaco' },
    { code: 'RU', label: 'Russia' },
    { code: 'SM', label: 'San Marino' },
    { code: 'AR', label: 'Argentina' },
    { code: 'BR', label: 'Brasile' },
    { code: 'CA', label: 'Canada' },
    { code: 'MX', label: 'Messico' },
    { code: 'US', label: 'Stati Uniti' },
    { code: 'CL', label: 'Cile' },
    { code: 'CO', label: 'Colombia' },
    { code: 'PE', label: 'Perù' },
    { code: 'UY', label: 'Uruguay' },
    { code: 'VE', label: 'Venezuela' },
    { code: 'AU', label: 'Australia' },
    { code: 'CN', label: 'Cina' },
    { code: 'KR', label: 'Corea del Sud' },
    { code: 'PH', label: 'Filippine' },
    { code: 'GE', label: 'Georgia' },
    { code: 'JP', label: 'Giappone' },
    { code: 'IN', label: 'India' },
    { code: 'ID', label: 'Indonesia' },
    { code: 'IL', label: 'Israele' },
    { code: 'KZ', label: 'Kazakistan' },
    { code: 'KG', label: 'Kirghizistan' },
    { code: 'KP', label: 'Corea del Nord' },
    { code: 'MY', label: 'Malaysia' },
    { code: 'NZ', label: 'Nuova Zelanda' },
    { code: 'PK', label: 'Pakistan' },
    { code: 'SG', label: 'Singapore' },
    { code: 'TH', label: 'Thailandia' },
    { code: 'VN', label: 'Vietnam' },
    { code: 'CU', label: 'Cuba' },
    { code: 'DO', label: 'Repubblica Dominicana' },
    { code: 'EC', label: 'Ecuador' },
    { code: 'GT', label: 'Guatemala' },
    { code: 'IR', label: 'Iran' },
    { code: 'PY', label: 'Paraguay' },
    { code: 'LK', label: 'Sri Lanka' },
    { code: 'ZA', label: 'Sudafrica' },
    { code: 'UZ', label: 'Uzbekistan' },
    { code: 'EG', label: 'Egitto' },
    { code: 'GH', label: 'Ghana' },
    { code: 'KE', label: 'Kenya' },
    { code: 'MU', label: 'Mauritius' },
    { code: 'NG', label: 'Nigeria' },
    { code: 'RW', label: 'Ruanda' },
    { code: 'TZ', label: 'Tanzania' },
    { code: 'UG', label: 'Uganda' },
    { code: 'ZM', label: 'Zambia' },
    { code: 'BD', label: 'Bangladesh' },
    { code: 'CR', label: 'Costa Rica' },
    { code: 'FJ', label: 'Figi' },
    { code: 'NP', label: 'Nepal' },
    { code: 'PG', label: 'Papua Nuova Guinea' },
    { code: 'AM', label: 'Armenia' },
    { code: 'GY', label: 'Guyana' },
    { code: 'HN', label: 'Honduras' },
    { code: 'JM', label: 'Giamaica' },
    { code: 'TT', label: 'Trinidad e Tobago' },
    { code: 'AZ', label: 'Azerbaigian' },
    { code: 'BZ', label: 'Belize' },
    { code: 'ET', label: 'Etiopia' },
    { code: 'KH', label: 'Cambogia' },
    { code: 'NA', label: 'Namibia' },
    { code: 'BB', label: 'Barbados' },
    { code: 'BO', label: 'Bolivia' },
    { code: 'SV', label: 'El Salvador' },
    { code: 'JO', label: 'Giordania' },
    { code: 'NI', label: 'Nicaragua' },
    { code: 'AE', label: 'Emirati Arabi Uniti' },
    { code: 'BH', label: 'Bahrein' },
    { code: 'KW', label: 'Kuwait' },
    { code: 'QA', label: 'Qatar' },
    { code: 'SA', label: 'Arabia Saudita' },
    { code: 'BN', label: 'Brunei' },
    { code: 'BS', label: 'Bahamas' },
    { code: 'NR', label: 'Nauru' },
    { code: 'VU', label: 'Vanuatu' },
    { code: 'VA', label: 'Citta del Vaticano' },
    { code: 'MA', label: 'Marocco' },
    { code: 'TN', label: 'Tunisia' },
    { code: 'BW', label: 'Botswana' },
    { code: 'MN', label: 'Mongolia' },
    { code: 'OM', label: 'Oman' },
    { code: 'AO', label: 'Angola' },
    { code: 'CV', label: 'Capo Verde' },
    { code: 'MZ', label: 'Mozambico' },
    { code: 'BT', label: 'Bhutan' },
    { code: 'PS', label: 'Palestina' },
    { code: 'DZ', label: 'Algeria' },
    { code: 'GN', label: 'Guinea' },
    { code: 'SN', label: 'Senegal' },
    { code: 'IQ', label: 'Iraq' },
    { code: 'AF', label: 'Afghanistan' },
    { code: 'HT', label: 'Haiti' },
    { code: 'TJ', label: 'Tagikistan' },
    { code: 'DM', label: 'Dominica' },
    { code: 'GD', label: 'Grenada' },
    { code: 'MH', label: 'Isole Marshall' },
    { code: 'MV', label: 'Maldive' },
    { code: 'WS', label: 'Samoa' },
    { code: 'AG', label: 'Antigua e Barbuda' },
    { code: 'KN', label: 'Saint Kitts e Nevis' },
    { code: 'BF', label: 'Burkina Faso' },
    { code: 'BI', label: 'Burundi' },
    { code: 'BJ', label: 'Benin' },
    { code: 'CF', label: 'Repubblica Centrafricana' },
    { code: 'CD', label: 'Repubblica Democratica del Congo' },
    { code: 'CG', label: 'Repubblica del Congo' },
    { code: 'CI', label: "Costa d'Avorio" },
    { code: 'CM', label: 'Camerun' },
    { code: 'GA', label: 'Gabon' },
    { code: 'GW', label: 'Guinea-Bissau' },
    { code: 'LA', label: 'Laos' },
    { code: 'LB', label: 'Libano' },
    { code: 'SR', label: 'Suriname' },
    { code: 'LC', label: 'Saint Lucia' },
    { code: 'LR', label: 'Liberia' },
    { code: 'LS', label: 'Lesotho' },
    { code: 'LY', label: 'Libia' },
    { code: 'MG', label: 'Madagascar' },
    { code: 'ML', label: 'Mali' },
    { code: 'MM', label: 'Myanmar' },
    { code: 'MR', label: 'Mauritania' },
    { code: 'MW', label: 'Malawi' },
    { code: 'SB', label: 'Isole Salomone' },
    { code: 'SC', label: 'Seychelles' },
    { code: 'SD', label: 'Sudan' },
    { code: 'SL', label: 'Sierra Leone' },
    { code: 'SS', label: 'Sud Sudan' },
    { code: 'ST', label: 'Sao Tome e Principe' },
    { code: 'SY', label: 'Siria' },
    { code: 'SZ', label: 'Eswatini' },
    { code: 'TG', label: 'Togo' },
    { code: 'TL', label: 'Timor Est' },
    { code: 'TV', label: 'Tuvalu' },
    { code: 'VC', label: 'Saint Vincent e Grenadine' },
    { code: 'PW', label: 'Palau' },
    { code: 'PA', label: 'Panama' },
    { code: 'FM', label: 'Micronesia' },
    { code: 'ZW', label: 'Zimbabwe' },
    { code: 'TD', label: 'Ciad' },
    { code: 'KM', label: 'Comore' },
    { code: 'DJ', label: 'Gibuti' },
    { code: 'GQ', label: 'Guinea Equatoriale' },
    { code: 'ER', label: 'Eritrea' },
    { code: 'GM', label: 'Gambia' },
    { code: 'NE', label: 'Niger' },
    { code: 'SO', label: 'Somalia' },
    { code: 'TM', label: 'Turkmenistan' },
    { code: 'YE', label: 'Yemen' },
    { code: 'KI', label: 'Kiribati' },
    { code: 'TO', label: 'Tonga' },
  ];

  protected readonly territories = [
    { code: 'FO', label: 'Isole Faroe' },
    { code: 'GG', label: 'Guernsey' },
    { code: 'GL', label: 'Groenlandia' },
    { code: 'HK', label: 'Hong Kong' },
    { code: 'JE', label: 'Jersey' },
    { code: 'PR', label: 'Porto Rico' },
    { code: 'TW', label: 'Taiwan' },
  ];

  protected readonly testCases: readonly TestCase[] = [
    {
      label: 'Codice valido',
      country: 'IT',
      value: 'RSSMRA85T10A562S',
      expectation: 'valid',
    },
    {
      label: 'Spazi e minuscole',
      country: 'IT',
      value: ' rssmra 85t10 a562s ',
      expectation: 'normalizzazione',
    },
    {
      label: 'Checksum errato',
      country: 'IT',
      value: 'RSSMRA85T10A562A',
      expectation: 'invalid_checksum',
    },
    {
      label: 'Formato errato',
      country: 'IT',
      value: '12345685T10A562S',
      expectation: 'invalid_format',
    },
    {
      label: 'Troppo corto',
      country: 'IT',
      value: 'RSSMRA85',
      expectation: 'invalid_length',
    },
    {
      label: 'Partita IVA valida',
      country: 'IT',
      value: '00743110157',
      expectation: 'valid',
    },
    {
      label: 'Partita IVA errata',
      country: 'IT',
      value: '00743110158',
      expectation: 'invalid_checksum',
    },
    {
      label: 'DNI spagnolo valido',
      country: 'ES',
      value: '12345678Z',
      expectation: 'valid',
    },
    {
      label: 'NIE spagnolo valido',
      country: 'ES',
      value: 'X1234567L',
      expectation: 'valid',
    },
    {
      label: 'DNI con lettera errata',
      country: 'ES',
      value: '12345678A',
      expectation: 'invalid_checksum',
    },
    {
      label: 'SPI francese valido',
      country: 'FR',
      value: '3023217600053',
      expectation: 'valid',
    },
    {
      label: 'SPI francese errato',
      country: 'FR',
      value: '3023217600054',
      expectation: 'invalid_checksum',
    },
    {
      label: 'NIF portoghese valido',
      country: 'PT',
      value: '123456789',
      expectation: 'valid',
    },
    {
      label: 'NIF portoghese errato',
      country: 'PT',
      value: '123456788',
      expectation: 'invalid_checksum',
    },
    {
      label: 'AFM greco valido',
      country: 'GR',
      value: '094259216',
      expectation: 'valid',
    },
    {
      label: 'AFM greco errato',
      country: 'GR',
      value: '094259217',
      expectation: 'invalid_checksum',
    },
    {
      label: 'Numero belga valido',
      country: 'BE',
      value: '85.07.30-033.28',
      expectation: 'valid',
    },
    {
      label: 'Numero belga errato',
      country: 'BE',
      value: '85073003329',
      expectation: 'invalid_checksum',
    },
    {
      label: 'OIB croato valido',
      country: 'HR',
      value: '12345678903',
      expectation: 'valid',
    },
    {
      label: 'OIB croato errato',
      country: 'HR',
      value: '12345678904',
      expectation: 'invalid_checksum',
    },
    {
      label: 'PESEL polacco valido',
      country: 'PL',
      value: '44051401458',
      expectation: 'valid',
    },
    {
      label: 'PESEL polacco errato',
      country: 'PL',
      value: '44051401459',
      expectation: 'invalid_checksum',
    },
    {
      label: 'HETU finlandese valido',
      country: 'FI',
      value: '131052-308T',
      expectation: 'valid',
    },
    {
      label: 'HETU finlandese errato',
      country: 'FI',
      value: '131052-308A',
      expectation: 'invalid_checksum',
    },
    {
      label: 'CPR danese valido',
      country: 'DK',
      value: '010101-1234',
      expectation: 'format',
    },
    {
      label: 'CPR con data errata',
      country: 'DK',
      value: '310299-1234',
      expectation: 'invalid_format',
    },
    {
      label: 'ID norvegese valido',
      country: 'NO',
      value: '01010100050',
      expectation: 'valid',
    },
    {
      label: 'ID norvegese errato',
      country: 'NO',
      value: '01010100051',
      expectation: 'invalid_checksum',
    },
    {
      label: 'Personnummer svedese valido',
      country: 'SE',
      value: '811228-9874',
      expectation: 'valid',
    },
    {
      label: 'Personnummer svedese errato',
      country: 'SE',
      value: '811228-9875',
      expectation: 'invalid_checksum',
    },
    {
      label: 'Kennitala islandese valida',
      country: 'IS',
      value: '120174-0029',
      expectation: 'valid',
    },
    {
      label: 'Kennitala islandese errata',
      country: 'IS',
      value: '120174-0039',
      expectation: 'invalid_checksum',
    },
    {
      label: 'Isikukood estone valido',
      country: 'EE',
      value: '37605030299',
      expectation: 'valid',
    },
    {
      label: 'Isikukood estone errato',
      country: 'EE',
      value: '37605030298',
      expectation: 'invalid_checksum',
    },
    {
      label: 'Codice lettone storico',
      country: 'LV',
      value: '010190-12349',
      expectation: 'valid',
    },
    {
      label: 'Codice lettone moderno',
      country: 'LV',
      value: '320000-12340',
      expectation: 'valid',
    },
    {
      label: 'Codice lituano valido',
      country: 'LT',
      value: '38409152012',
      expectation: 'valid',
    },
    {
      label: 'Codice lituano errato',
      country: 'LT',
      value: '38409152013',
      expectation: 'invalid_checksum',
    },
    {
      label: 'BSN olandese valido',
      country: 'NL',
      value: '123456782',
      expectation: 'valid',
    },
    {
      label: 'BSN olandese errato',
      country: 'NL',
      value: '123456783',
      expectation: 'invalid_checksum',
    },
    {
      label: 'Rodné číslo ceco valido',
      country: 'CZ',
      value: '800101/0006',
      expectation: 'valid',
    },
    {
      label: 'Rodné číslo slovacco valido',
      country: 'SK',
      value: '800101/0006',
      expectation: 'valid',
    },
    {
      label: 'Rodné číslo storico',
      country: 'CZ',
      value: '530101/123',
      expectation: 'format',
    },
    {
      label: 'Numero fiscale sloveno',
      country: 'SI',
      value: '12345679',
      expectation: 'valid',
    },
    {
      label: 'Numero sloveno errato',
      country: 'SI',
      value: '12345678',
      expectation: 'invalid_checksum',
    },
    {
      label: 'TIN austriaco',
      country: 'AT',
      value: '12-345/6789',
      expectation: 'format',
    },
    {
      label: 'IdNr tedesca valida',
      country: 'DE',
      value: '12345678911',
      expectation: 'valid',
    },
    {
      label: 'IdNr tedesca errata',
      country: 'DE',
      value: '12345678912',
      expectation: 'invalid_checksum',
    },
    {
      label: 'AVS svizzera valida',
      country: 'CH',
      value: '756.1234.5678.97',
      expectation: 'valid',
    },
    {
      label: 'AVS svizzera errata',
      country: 'CH',
      value: '756.1234.5678.98',
      expectation: 'invalid_checksum',
    },
    {
      label: 'Tax ID ungherese',
      country: 'HU',
      value: '8123456786',
      expectation: 'valid',
    },
    {
      label: 'Tax ID ungherese errato',
      country: 'HU',
      value: '8123456787',
      expectation: 'invalid_checksum',
    },
    {
      label: 'CNP romeno valido',
      country: 'RO',
      value: '1960523420017',
      expectation: 'valid',
    },
    {
      label: 'CNP romeno errato',
      country: 'RO',
      value: '1960523420018',
      expectation: 'invalid_checksum',
    },
    {
      label: 'EGN bulgaro valido',
      country: 'BG',
      value: '0041010002',
      expectation: 'valid',
    },
    {
      label: 'EGN bulgaro errato',
      country: 'BG',
      value: '0041010003',
      expectation: 'invalid_checksum',
    },
    {
      label: 'JMBG serbo valido',
      country: 'RS',
      value: '0101006710000',
      expectation: 'valid',
    },
    {
      label: 'JMBG serbo errato',
      country: 'RS',
      value: '0101006710001',
      expectation: 'invalid_checksum',
    },
    {
      label: 'JMBG montenegrino valido',
      country: 'ME',
      value: '0101006210008',
      expectation: 'valid',
    },
    {
      label: 'JMBG montenegrino errato',
      country: 'ME',
      value: '0101006210009',
      expectation: 'invalid_checksum',
    },
    {
      label: 'EMBG macedone valido',
      country: 'MK',
      value: '0101006410007',
      expectation: 'valid',
    },
    {
      label: 'EMBG macedone errato',
      country: 'MK',
      value: '0101006410008',
      expectation: 'invalid_checksum',
    },
    {
      label: 'Numero personale albanese',
      country: 'AL',
      value: 'K30315001A',
      expectation: 'format',
    },
    {
      label: 'Numero albanese con data errata',
      country: 'AL',
      value: 'K30230001A',
      expectation: 'invalid_format',
    },
    {
      label: 'JMBG bosniaco valido',
      country: 'BA',
      value: '0101006170006',
      expectation: 'valid',
    },
    {
      label: 'JMBG bosniaco errato',
      country: 'BA',
      value: '0101006170007',
      expectation: 'invalid_checksum',
    },
    {
      label: 'T.C. Kimlik No. valido',
      country: 'TR',
      value: '10000000146',
      expectation: 'valid',
    },
    {
      label: 'T.C. Kimlik No. errato',
      country: 'TR',
      value: '10000000147',
      expectation: 'invalid_checksum',
    },
    {
      label: 'IDNP moldavo',
      country: 'MD',
      value: '2002001000001',
      expectation: 'format',
    },
    {
      label: 'IDNP moldavo errato',
      country: 'MD',
      value: '0000000000000',
      expectation: 'invalid_format',
    },
    {
      label: 'Numero fiscale ucraino',
      country: 'UA',
      value: '1234567890',
      expectation: 'format',
    },
    {
      label: 'Numero ucraino errato',
      country: 'UA',
      value: '123456789A',
      expectation: 'invalid_format',
    },
    {
      label: 'TIN cipriota',
      country: 'CY',
      value: '12345678T',
      expectation: 'format',
    },
    {
      label: 'TIN cipriota errato',
      country: 'CY',
      value: '123456789',
      expectation: 'invalid_format',
    },
    {
      label: 'PPS irlandese valido',
      country: 'IE',
      value: '1234567T',
      expectation: 'valid',
    },
    {
      label: 'PPS irlandese errato',
      country: 'IE',
      value: '1234567A',
      expectation: 'invalid_checksum',
    },
    {
      label: 'Matricola lussemburghese',
      country: 'LU',
      value: '2000010100125',
      expectation: 'valid',
    },
    {
      label: 'Matricola lussemburghese errata',
      country: 'LU',
      value: '2000010100126',
      expectation: 'invalid_checksum',
    },
    {
      label: 'TIN maltese',
      country: 'MT',
      value: '1234567M',
      expectation: 'format',
    },
    {
      label: 'TIN maltese errato',
      country: 'MT',
      value: '1234567X',
      expectation: 'invalid_format',
    },
    {
      label: 'PEID Liechtenstein',
      country: 'LI',
      value: '000247681888',
      expectation: 'format',
    },
    {
      label: 'PEID Liechtenstein errato',
      country: 'LI',
      value: '000000000000',
      expectation: 'invalid_format',
    },
    {
      label: 'NRT andorrano',
      country: 'AD',
      value: 'F123456Z',
      expectation: 'format',
    },
    {
      label: 'NRT andorrano errato',
      country: 'AD',
      value: 'F000000Z',
      expectation: 'invalid_format',
    },
    {
      label: 'NINO britannico',
      country: 'GB',
      value: 'AB123456C',
      expectation: 'format',
    },
    {
      label: 'NINO britannico errato',
      country: 'GB',
      value: 'AB123456E',
      expectation: 'invalid_format',
    },
    {
      label: 'INN russo valido',
      country: 'RU',
      value: '7728168971',
      expectation: 'valid',
    },
    {
      label: 'INN russo errato',
      country: 'RU',
      value: '7728168972',
      expectation: 'invalid_checksum',
    },
    {
      label: 'UNP bielorusso',
      country: 'BY',
      value: '123456789',
      expectation: 'format',
    },
    {
      label: 'UNP bielorusso errato',
      country: 'BY',
      value: '12345678',
      expectation: 'invalid_length',
    },
    {
      label: 'Codice ISS San Marino',
      country: 'SM',
      value: '123456789',
      expectation: 'format',
    },
    {
      label: 'Codice ISS San Marino errato',
      country: 'SM',
      value: '1234',
      expectation: 'invalid_format',
    },
    {
      label: 'TIN Monaco',
      country: 'MC',
      value: 'FR12345678901',
      expectation: 'format',
    },
    {
      label: 'TIN Monaco errato',
      country: 'MC',
      value: '1234',
      expectation: 'invalid_format',
    },
    {
      label: 'SSN statunitense',
      country: 'US',
      value: '123456789',
      expectation: 'format',
    },
    {
      label: 'SSN statunitense errato',
      country: 'US',
      value: '000456789',
      expectation: 'invalid_format',
    },
    {
      label: 'SIN canadese',
      country: 'CA',
      value: '046454286',
      expectation: 'valid',
    },
    {
      label: 'SIN canadese errato',
      country: 'CA',
      value: '046454287',
      expectation: 'invalid_checksum',
    },
    {
      label: 'CPF brasiliano',
      country: 'BR',
      value: '11144477735',
      expectation: 'valid',
    },
    {
      label: 'CPF brasiliano errato',
      country: 'BR',
      value: '11144477736',
      expectation: 'invalid_checksum',
    },
    {
      label: 'RFC messicano',
      country: 'MX',
      value: 'GODE561231GR8',
      expectation: 'valid',
    },
    {
      label: 'RFC messicano errato',
      country: 'MX',
      value: 'GODE561231GR9',
      expectation: 'invalid_checksum',
    },
    {
      label: 'CUIT/CUIL argentino',
      country: 'AR',
      value: '20267565393',
      expectation: 'valid',
    },
    {
      label: 'CUIT argentino errato',
      country: 'AR',
      value: '20267565394',
      expectation: 'invalid_checksum',
    },
    {
      label: 'RUT cileno',
      country: 'CL',
      value: '123456785',
      expectation: 'valid',
    },
    {
      label: 'RUT cileno con K',
      country: 'CL',
      value: '1111122K',
      expectation: 'valid',
    },
    {
      label: 'RUT cileno errato',
      country: 'CL',
      value: '123456786',
      expectation: 'invalid_checksum',
    },
    {
      label: 'NIT colombiano',
      country: 'CO',
      value: '8903215670',
      expectation: 'valid',
    },
    {
      label: 'NIT colombiano errato',
      country: 'CO',
      value: '8903215671',
      expectation: 'invalid_checksum',
    },
    {
      label: 'DNI peruviano',
      country: 'PE',
      value: '100000008',
      expectation: 'valid',
    },
    {
      label: 'RUC peruviano',
      country: 'PE',
      value: '20100000009',
      expectation: 'valid',
    },
    {
      label: 'RUC peruviano errato',
      country: 'PE',
      value: '20100000008',
      expectation: 'invalid_checksum',
    },
    {
      label: 'CI uruguaiana',
      country: 'UY',
      value: '12345672',
      expectation: 'valid',
    },
    {
      label: 'CI uruguaiana errato',
      country: 'UY',
      value: '12345673',
      expectation: 'invalid_checksum',
    },
    {
      label: 'RIF venezuelano',
      country: 'VE',
      value: 'J070133805',
      expectation: 'valid',
    },
    {
      label: 'RIF venezuelano errato',
      country: 'VE',
      value: 'J070133806',
      expectation: 'invalid_checksum',
    },
    {
      label: 'TFN australiano',
      country: 'AU',
      value: '123456782',
      expectation: 'valid',
    },
    {
      label: 'TFN australiano errato',
      country: 'AU',
      value: '123456783',
      expectation: 'invalid_checksum',
    },
    {
      label: 'ID cinese valido',
      country: 'CN',
      value: '11010519491231002X',
      expectation: 'valid',
    },
    {
      label: 'ID cinese errato',
      country: 'CN',
      value: '110105194912310021',
      expectation: 'invalid_checksum',
    },
    {
      label: 'RRN sudcoreano',
      country: 'KR',
      value: '900101-1234567',
      expectation: 'format',
    },
    {
      label: 'RRN con data errata',
      country: 'KR',
      value: '901301-1234567',
      expectation: 'invalid_format',
    },
    {
      label: 'My Number giapponese',
      country: 'JP',
      value: '123456789018',
      expectation: 'valid',
    },
    {
      label: 'My Number giapponese errato',
      country: 'JP',
      value: '123456789019',
      expectation: 'invalid_checksum',
    },
    {
      label: 'PAN indiano',
      country: 'IN',
      value: 'ABCPE1234F',
      expectation: 'format',
    },
    {
      label: 'PAN indiano errato',
      country: 'IN',
      value: 'ABCXE1234F',
      expectation: 'invalid_format',
    },
    {
      label: 'ID israeliano valido',
      country: 'IL',
      value: '123456782',
      expectation: 'valid',
    },
    {
      label: 'ID israeliano errato',
      country: 'IL',
      value: '123456783',
      expectation: 'invalid_checksum',
    },
    {
      label: 'IRD neozelandese',
      country: 'NZ',
      value: '49-091-850',
      expectation: 'valid',
    },
    {
      label: 'IRD neozelandese errato',
      country: 'NZ',
      value: '49091851',
      expectation: 'invalid_checksum',
    },
    {
      label: 'NRIC di Singapore',
      country: 'SG',
      value: 'S1234567D',
      expectation: 'valid',
    },
    {
      label: 'NRIC di Singapore errato',
      country: 'SG',
      value: 'S1234567A',
      expectation: 'invalid_checksum',
    },
    {
      label: 'ID thailandese',
      country: 'TH',
      value: '1101700230708',
      expectation: 'valid',
    },
    {
      label: 'ID thailandese errato',
      country: 'TH',
      value: '1101700230709',
      expectation: 'invalid_checksum',
    },
    {
      label: 'Numero personale georgiano',
      country: 'GE',
      value: '12345678901',
      expectation: 'format',
    },
    {
      label: 'Numero georgiano troppo corto',
      country: 'GE',
      value: '1234567890',
      expectation: 'invalid_length',
    },
    {
      label: 'NPWP indonesiano',
      country: 'ID',
      value: '01.300.066.6-091.000',
      expectation: 'valid',
    },
    {
      label: 'NPWP indonesiano errato',
      country: 'ID',
      value: '013000667091000',
      expectation: 'invalid_checksum',
    },
    {
      label: 'NIK indonesiano',
      country: 'ID',
      value: '3171011708450001',
      expectation: 'format',
    },
    {
      label: 'IIN kazako valido',
      country: 'KZ',
      value: '900101300007',
      expectation: 'valid',
    },
    {
      label: 'IIN kazako errato',
      country: 'KZ',
      value: '900101300008',
      expectation: 'invalid_checksum',
    },
    {
      label: 'INN kirghiso',
      country: 'KG',
      value: '10101199000001',
      expectation: 'format',
    },
    {
      label: 'INN kirghiso con data errata',
      country: 'KG',
      value: '10113199000001',
      expectation: 'invalid_format',
    },
    {
      label: 'NRIC malese',
      country: 'MY',
      value: '850101-14-5678',
      expectation: 'format',
    },
    {
      label: 'NRIC malese con data errata',
      country: 'MY',
      value: '851301145678',
      expectation: 'invalid_format',
    },
    {
      label: 'TIN filippino',
      country: 'PH',
      value: '123456789',
      expectation: 'format',
    },
    {
      label: 'TIN filippino troppo corto',
      country: 'PH',
      value: '12345678',
      expectation: 'invalid_length',
    },
    {
      label: 'CNIC pakistano',
      country: 'PK',
      value: '1234512345671',
      expectation: 'format',
    },
    {
      label: 'CNIC pakistano errato',
      country: 'PK',
      value: '0234512345671',
      expectation: 'invalid_format',
    },
    {
      label: 'Codice fiscale vietnamita',
      country: 'VN',
      value: '0123456789',
      expectation: 'format',
    },
    {
      label: 'Codice vietnamita troppo corto',
      country: 'VN',
      value: '012345678',
      expectation: 'invalid_length',
    },
    {
      label: 'Tax reference sudafricano',
      country: 'ZA',
      value: '0001339050',
      expectation: 'valid',
    },
    {
      label: 'Tax reference sudafricano errato',
      country: 'ZA',
      value: '0001339051',
      expectation: 'invalid_checksum',
    },
    {
      label: 'ID sudafricano (13 cifre)',
      country: 'ZA',
      value: '9405105678082',
      expectation: 'valid',
    },
    {
      label: 'Codice nazionale iraniano',
      country: 'IR',
      value: '1234567891',
      expectation: 'valid',
    },
    {
      label: 'Codice iraniano errato',
      country: 'IR',
      value: '1234567892',
      expectation: 'invalid_checksum',
    },
    {
      label: 'Cédula ecuadoriana',
      country: 'EC',
      value: '1714616123',
      expectation: 'valid',
    },
    {
      label: 'RUC personale ecuadoriano',
      country: 'EC',
      value: '1714616123001',
      expectation: 'valid',
    },
    {
      label: 'Cédula ecuadoriana errata',
      country: 'EC',
      value: '1714616124',
      expectation: 'invalid_checksum',
    },
    {
      label: 'Cédula dominicana',
      country: 'DO',
      value: '00100082700',
      expectation: 'valid',
    },
    {
      label: 'Cédula dominicana errata',
      country: 'DO',
      value: '00100082701',
      expectation: 'invalid_checksum',
    },
    {
      label: 'RUC paraguaiano',
      country: 'PY',
      value: '3966931-9',
      expectation: 'valid',
    },
    {
      label: 'RUC paraguaiano errato',
      country: 'PY',
      value: '39669318',
      expectation: 'invalid_checksum',
    },
    {
      label: 'NIT guatemalteco',
      country: 'GT',
      value: '3602978-5',
      expectation: 'valid',
    },
    {
      label: 'NIT guatemalteco con K',
      country: 'GT',
      value: '576937K',
      expectation: 'valid',
    },
    {
      label: 'NIT guatemalteco errato',
      country: 'GT',
      value: '36029786',
      expectation: 'invalid_checksum',
    },
    {
      label: 'NIC srilankese storico',
      country: 'LK',
      value: '790930622V',
      expectation: 'format',
    },
    {
      label: 'NIC srilankese errato',
      country: 'LK',
      value: '794430622V',
      expectation: 'invalid_format',
    },
    {
      label: 'PINFL uzbeko',
      country: 'UZ',
      value: '30101901234567',
      expectation: 'format',
    },
    {
      label: 'PINFL uzbeko con data errata',
      country: 'UZ',
      value: '30113901234567',
      expectation: 'invalid_format',
    },
    {
      label: 'Carnet de identidad cubano',
      country: 'CU',
      value: '90010112345',
      expectation: 'format',
    },
    {
      label: 'Carnet cubano con data errata',
      country: 'CU',
      value: '90130112345',
      expectation: 'invalid_format',
    },
    {
      label: 'TIN egiziano',
      country: 'EG',
      value: '123456789',
      expectation: 'format',
    },
    {
      label: 'TIN egiziano errato',
      country: 'EG',
      value: '000000000',
      expectation: 'invalid_format',
    },
    {
      label: 'GhanaCard PIN',
      country: 'GH',
      value: 'GHA1234567890',
      expectation: 'format',
    },
    {
      label: 'GhanaCard PIN errato',
      country: 'GH',
      value: 'GHA12345A7890',
      expectation: 'invalid_format',
    },
    {
      label: 'KRA PIN keniota',
      country: 'KE',
      value: 'A123456789B',
      expectation: 'format',
    },
    {
      label: 'KRA PIN keniota errato',
      country: 'KE',
      value: 'B123456789B',
      expectation: 'invalid_format',
    },
    {
      label: 'TAN mauriziano',
      country: 'MU',
      value: '12345678',
      expectation: 'format',
    },
    {
      label: 'TAN mauriziano errato',
      country: 'MU',
      value: '00000000',
      expectation: 'invalid_format',
    },
    {
      label: 'TIN nigeriano',
      country: 'NG',
      value: '1234567890',
      expectation: 'format',
    },
    {
      label: 'TIN nigeriano errato',
      country: 'NG',
      value: '0000000000',
      expectation: 'invalid_format',
    },
    {
      label: 'TIN ruandese',
      country: 'RW',
      value: '123456789',
      expectation: 'format',
    },
    {
      label: 'TIN ruandese errato',
      country: 'RW',
      value: '000000000',
      expectation: 'invalid_format',
    },
    {
      label: 'TIN tanzaniano',
      country: 'TZ',
      value: '123456789',
      expectation: 'format',
    },
    {
      label: 'TIN tanzaniano errato',
      country: 'TZ',
      value: '000000000',
      expectation: 'invalid_format',
    },
    {
      label: 'TIN ugandese',
      country: 'UG',
      value: '1234567890',
      expectation: 'format',
    },
    {
      label: 'TIN ugandese errato',
      country: 'UG',
      value: '0000000000',
      expectation: 'invalid_format',
    },
    {
      label: 'TPIN zambiano',
      country: 'ZM',
      value: '1234567890',
      expectation: 'format',
    },
    {
      label: 'TPIN zambiano errato',
      country: 'ZM',
      value: '0000000000',
      expectation: 'invalid_format',
    },
    {
      label: 'Cédula costaricana',
      country: 'CR',
      value: '123456789',
      expectation: 'format',
    },
    {
      label: 'Cédula costaricana errata',
      country: 'CR',
      value: '023456789',
      expectation: 'invalid_format',
    },
    {
      label: 'eTIN bengalese',
      country: 'BD',
      value: '123456789012',
      expectation: 'format',
    },
    {
      label: 'eTIN bengalese errato',
      country: 'BD',
      value: '000000000000',
      expectation: 'invalid_format',
    },
    {
      label: 'PAN nepalese',
      country: 'NP',
      value: '123456789',
      expectation: 'format',
    },
    {
      label: 'PAN nepalese errato',
      country: 'NP',
      value: '000000000',
      expectation: 'invalid_format',
    },
    {
      label: 'TIN figiano',
      country: 'FJ',
      value: '123456789',
      expectation: 'format',
    },
    {
      label: 'TIN figiano errato',
      country: 'FJ',
      value: '000000000',
      expectation: 'invalid_format',
    },
    {
      label: 'TIN Papua Nuova Guinea',
      country: 'PG',
      value: '123456789',
      expectation: 'format',
    },
    {
      label: 'TIN Papua Nuova Guinea errato',
      country: 'PG',
      value: '000000000',
      expectation: 'invalid_format',
    },
    {
      label: 'TRN giamaicano',
      country: 'JM',
      value: '123456789',
      expectation: 'format',
    },
    {
      label: 'TRN giamaicano errato',
      country: 'JM',
      value: '000000000',
      expectation: 'invalid_format',
    },
    {
      label: 'BIR Trinidad e Tobago',
      country: 'TT',
      value: '1234567890',
      expectation: 'format',
    },
    {
      label: 'BIR Trinidad e Tobago errato',
      country: 'TT',
      value: '0000000000',
      expectation: 'invalid_format',
    },
    {
      label: 'TIN guyanese',
      country: 'GY',
      value: '123456789',
      expectation: 'format',
    },
    {
      label: 'TIN guyanese errato',
      country: 'GY',
      value: '000000000',
      expectation: 'invalid_format',
    },
    {
      label: 'RTN honduregno',
      country: 'HN',
      value: '08011990123456',
      expectation: 'format',
    },
    {
      label: 'RTN honduregno errato',
      country: 'HN',
      value: '00000000000000',
      expectation: 'invalid_format',
    },
    {
      label: 'PSN armeno',
      country: 'AM',
      value: '1234567890',
      expectation: 'format',
    },
    {
      label: 'PSN armeno errato',
      country: 'AM',
      value: '0000000000',
      expectation: 'invalid_format',
    },
    {
      label: 'TIN etiope',
      country: 'ET',
      value: '1234567890',
      expectation: 'format',
    },
    {
      label: 'TIN etiope errato',
      country: 'ET',
      value: '0000000000',
      expectation: 'invalid_format',
    },
    {
      label: 'TIN namibiano',
      country: 'NA',
      value: '123456789',
      expectation: 'format',
    },
    {
      label: 'TIN namibiano errato',
      country: 'NA',
      value: '000000000',
      expectation: 'invalid_format',
    },
    {
      label: 'TIN Belize',
      country: 'BZ',
      value: '123456',
      expectation: 'format',
    },
    {
      label: 'TIN Belize errato',
      country: 'BZ',
      value: '000000',
      expectation: 'invalid_format',
    },
    {
      label: 'VÖEN azero',
      country: 'AZ',
      value: '1234567890',
      expectation: 'format',
    },
    {
      label: 'VÖEN azero errato',
      country: 'AZ',
      value: '0000000000',
      expectation: 'invalid_format',
    },
    {
      label: 'TIN cambogiano',
      country: 'KH',
      value: '123456789',
      expectation: 'format',
    },
    {
      label: 'TIN cambogiano errato',
      country: 'KH',
      value: '000000000',
      expectation: 'invalid_format',
    },
    {
      label: 'TIN Barbados',
      country: 'BB',
      value: '1234567890123',
      expectation: 'format',
    },
    {
      label: 'TIN Barbados errato',
      country: 'BB',
      value: '0000000000000',
      expectation: 'invalid_format',
    },
    {
      label: 'NIT salvadoregno',
      country: 'SV',
      value: '0614-241287-102-5',
      expectation: 'format',
    },
    {
      label: 'NIT salvadoregno con data errata',
      country: 'SV',
      value: '0614-321287-102-5',
      expectation: 'invalid_format',
    },
    {
      label: 'RUC nicaraguense',
      country: 'NI',
      value: '001-241287-1234A',
      expectation: 'format',
    },
    {
      label: 'RUC nicaraguense con data errata',
      country: 'NI',
      value: '001-321287-1234A',
      expectation: 'invalid_format',
    },
    {
      label: 'TIN giordano',
      country: 'JO',
      value: '123456789',
      expectation: 'format',
    },
    {
      label: 'TIN giordano errato',
      country: 'JO',
      value: '000000000',
      expectation: 'invalid_format',
    },
    {
      label: 'NIT boliviano',
      country: 'BO',
      value: '1234567',
      expectation: 'format',
    },
    {
      label: 'NIT boliviano errato',
      country: 'BO',
      value: '0000000',
      expectation: 'invalid_format',
    },
    {
      label: 'Emirati Arabi Uniti senza TIN personale',
      country: 'AE',
      value: '123456789',
      expectation: 'not_applicable',
    },
    {
      label: 'Bahrein senza TIN personale',
      country: 'BH',
      value: '123456789',
      expectation: 'not_applicable',
    },
    {
      label: 'Kuwait senza TIN personale',
      country: 'KW',
      value: '123456789',
      expectation: 'not_applicable',
    },
    {
      label: 'Qatar senza TIN personale',
      country: 'QA',
      value: '123456789',
      expectation: 'not_applicable',
    },
    {
      label: 'Arabia Saudita senza TIN personale',
      country: 'SA',
      value: '123456789',
      expectation: 'not_applicable',
    },
    {
      label: 'Brunei senza TIN personale',
      country: 'BN',
      value: '123456789',
      expectation: 'not_applicable',
    },
    {
      label: 'Bahamas senza TIN personale',
      country: 'BS',
      value: '123456789',
      expectation: 'not_applicable',
    },
    {
      label: 'Nauru senza TIN personale generalizzato',
      country: 'NR',
      value: '123456789',
      expectation: 'not_applicable',
    },
    {
      label: 'Vanuatu senza TIN personale generalizzato',
      country: 'VU',
      value: '123456789',
      expectation: 'not_applicable',
    },
    {
      label: 'Vaticano senza TIN personale',
      country: 'VA',
      value: '123456789',
      expectation: 'not_applicable',
    },
    {
      label: 'Identifiant fiscal marocchino',
      country: 'MA',
      value: '12345678',
      expectation: 'format',
    },
    {
      label: 'Identifiant fiscal marocchino errato',
      country: 'MA',
      value: '00000000',
      expectation: 'invalid_format',
    },
    {
      label: 'Matricule fiscal tunisino',
      country: 'TN',
      value: '1234567/A/M/000',
      expectation: 'format',
    },
    {
      label: 'Matricule fiscal tunisino errato',
      country: 'TN',
      value: '0000000/A/M/000',
      expectation: 'invalid_format',
    },
    {
      label: 'Omang botswanese',
      country: 'BW',
      value: '123456789',
      expectation: 'format',
    },
    {
      label: 'Omang botswanese errato',
      country: 'BW',
      value: '000000000',
      expectation: 'invalid_format',
    },
    {
      label: 'Registro civile mongolo',
      country: 'MN',
      value: 'УБ90103112',
      expectation: 'format',
    },
    {
      label: 'Registro civile mongolo con data errata',
      country: 'MN',
      value: 'УБ90323112',
      expectation: 'invalid_format',
    },
    {
      label: 'Oman prima della riforma 2028',
      country: 'OM',
      value: '123456789',
      expectation: 'not_applicable',
    },
    {
      label: 'NIF angolano',
      country: 'AO',
      value: '1234567890',
      expectation: 'format',
    },
    {
      label: 'NIF angolano errato',
      country: 'AO',
      value: '0000000000',
      expectation: 'invalid_format',
    },
    {
      label: 'NIF capoverdiano',
      country: 'CV',
      value: '501442600',
      expectation: 'valid',
    },
    {
      label: 'NIF capoverdiano con checksum errato',
      country: 'CV',
      value: '501442601',
      expectation: 'invalid_checksum',
    },
    {
      label: 'NUIT mozambicano',
      country: 'MZ',
      value: '123456789',
      expectation: 'format',
    },
    {
      label: 'NUIT mozambicano errato',
      country: 'MZ',
      value: '000000000',
      expectation: 'invalid_format',
    },
    {
      label: 'CID bhutanese',
      country: 'BT',
      value: '12345678901',
      expectation: 'format',
    },
    {
      label: 'CID bhutanese errato',
      country: 'BT',
      value: '00000000000',
      expectation: 'invalid_format',
    },
    {
      label: 'Numero identita palestinese',
      country: 'PS',
      value: '123456782',
      expectation: 'valid',
    },
    {
      label: 'Numero identita palestinese errato',
      country: 'PS',
      value: '123456783',
      expectation: 'invalid_checksum',
    },
    {
      label: 'NIF algerino',
      country: 'DZ',
      value: '408 020 000 150 039',
      expectation: 'format',
    },
    {
      label: 'NIF algerino di stabilimento secondario',
      country: 'DZ',
      value: '41201600000606600001',
      expectation: 'format',
    },
    {
      label: 'NIFp guineano',
      country: 'GN',
      value: '693-770-885',
      expectation: 'valid',
    },
    {
      label: 'NIFp guineano errato',
      country: 'GN',
      value: '693770880',
      expectation: 'invalid_checksum',
    },
    {
      label: 'NINEA senegalese con COFI',
      country: 'SN',
      value: '3067221 2G2',
      expectation: 'valid',
    },
    {
      label: 'NINEA senegalese errato',
      country: 'SN',
      value: '3067222',
      expectation: 'invalid_checksum',
    },
    {
      label: 'Iraq TIN valido',
      country: 'IQ',
      value: '377819054',
      expectation: 'valid',
    },
    {
      label: 'Iraq TIN non valido (tutti zeri)',
      country: 'IQ',
      value: '000000000',
      expectation: 'invalid_format',
    },
    {
      label: 'Afghanistan e-Tazkira valido',
      country: 'AF',
      value: '1234-5678-90123',
      expectation: 'valid',
    },
    {
      label: 'Afghanistan e-Tazkira non valido',
      country: 'AF',
      value: '0000000000000',
      expectation: 'invalid_format',
    },
    {
      label: 'Haiti NIF valido',
      country: 'HT',
      value: '123-456-7890',
      expectation: 'valid',
    },
    {
      label: 'Haiti NIF non valido',
      country: 'HT',
      value: '0000000000',
      expectation: 'invalid_format',
    },
    {
      label: 'Tagikistan INN valido',
      country: 'TJ',
      value: '123-456-789',
      expectation: 'valid',
    },
    {
      label: 'Tagikistan INN non valido',
      country: 'TJ',
      value: '000000000',
      expectation: 'invalid_format',
    },
    {
      label: 'Dominica taxpayer number valido',
      country: 'DM',
      value: '123456',
      expectation: 'valid',
    },
    {
      label: 'Dominica taxpayer number non valido',
      country: 'DM',
      value: '000000',
      expectation: 'invalid_format',
    },
    {
      label: 'Grenada TIN valido',
      country: 'GD',
      value: '123-456',
      expectation: 'valid',
    },
    {
      label: 'Grenada TIN non valido',
      country: 'GD',
      value: '000000',
      expectation: 'invalid_format',
    },
    {
      label: 'Isole Marshall employee ID valido',
      country: 'MH',
      value: '04-086123',
      expectation: 'valid',
    },
    {
      label: 'Isole Marshall employee ID non valido',
      country: 'MH',
      value: '05-086123',
      expectation: 'invalid_format',
    },
    {
      label: 'Maldive TIN valido',
      country: 'MV',
      value: '1099060',
      expectation: 'valid',
    },
    {
      label: 'Maldive TIN non valido (tutti zeri)',
      country: 'MV',
      value: '0000000',
      expectation: 'invalid_format',
    },
    {
      label: 'Samoa TIN valido (5 cifre)',
      country: 'WS',
      value: '70004',
      expectation: 'valid',
    },
    {
      label: 'Samoa TIN valido (9 cifre)',
      country: 'WS',
      value: '123456789',
      expectation: 'valid',
    },
    {
      label: 'Samoa TIN troppo corto',
      country: 'WS',
      value: '1234',
      expectation: 'invalid_length',
    },
    {
      label: 'Antigua e Barbuda senza TIN personale',
      country: 'AG',
      value: '123456789',
      expectation: 'not_applicable',
    },
    {
      label: 'Saint Kitts e Nevis senza TIN personale',
      country: 'KN',
      value: '123456789',
      expectation: 'not_applicable',
    },
    { label: 'Burkina Faso IFU', country: 'BF', value: '12345678A', expectation: 'format' },
    { label: 'Burundi NIF', country: 'BI', value: '1234567890', expectation: 'format' },
    { label: 'Benin IFU', country: 'BJ', value: '1234567890123', expectation: 'format' },
    { label: 'Repubblica Centrafricana NIF', country: 'CF', value: '1234567A', expectation: 'format' },
    { label: 'RDC NIF', country: 'CD', value: 'A1011126F', expectation: 'format' },
    { label: 'Repubblica del Congo NIU', country: 'CG', value: 'A1234567890123456', expectation: 'format' },
    { label: "Costa d'Avorio contribuente", country: 'CI', value: '1234567A', expectation: 'format' },
    { label: 'Camerun NIU personale', country: 'CM', value: 'P123456789012A', expectation: 'format' },
    { label: 'Gabon NIF', country: 'GA', value: '1234567890123', expectation: 'format' },
    { label: 'Guinea-Bissau NIF', country: 'GW', value: '123456789', expectation: 'format' },
    { label: 'Laos TIN', country: 'LA', value: '12345678901', expectation: 'format' },
    { label: 'Libano TIN IVA', country: 'LB', value: '123456-601', expectation: 'format' },
    { label: 'Suriname FIN', country: 'SR', value: '1234567890', expectation: 'format' },
    { label: 'Saint Lucia TIN', country: 'LC', value: '123456', expectation: 'format' },
    { label: 'Liberia TIN', country: 'LR', value: '123456789', expectation: 'format' },
    { label: 'Lesotho TIN', country: 'LS', value: '12345678', expectation: 'format' },
    { label: 'Libia numero nazionale', country: 'LY', value: '112345678901', expectation: 'format' },
    { label: 'Madagascar NIF', country: 'MG', value: '1234567890', expectation: 'format' },
    { label: 'Mali NIF', country: 'ML', value: '123456789A', expectation: 'format' },
    { label: 'Myanmar TIN', country: 'MM', value: '123456789', expectation: 'format' },
    { label: 'Mauritania NIF', country: 'MR', value: '12345678', expectation: 'format' },
    { label: 'Malawi TPIN', country: 'MW', value: 'TP12345678', expectation: 'format' },
    { label: 'Isole Salomone TIN', country: 'SB', value: '123456789', expectation: 'format' },
    { label: 'Seychelles TIN personale', country: 'SC', value: '122456789', expectation: 'format' },
    { label: 'Sierra Leone TIN', country: 'SL', value: '12345678', expectation: 'format' },
    { label: 'Sud Sudan TIN', country: 'SS', value: '123456789', expectation: 'format' },
    { label: 'Sao Tome NIF', country: 'ST', value: '123456789', expectation: 'format' },
    { label: 'Siria TIN', country: 'SY', value: '12345678901', expectation: 'format' },
    { label: 'Eswatini TIN', country: 'SZ', value: '123456789', expectation: 'format' },
    { label: 'Togo NIF personale', country: 'TG', value: '0123456789012', expectation: 'format' },
    { label: 'Timor Est TIN', country: 'TL', value: '123456789', expectation: 'format' },
    { label: 'Tuvalu senza TIN personale', country: 'TV', value: '123456789', expectation: 'not_applicable' },
    { label: 'Saint Vincent TIN', country: 'VC', value: '123456789', expectation: 'format' },
    { label: 'Palau ROP SS Number', country: 'PW', value: '006-123456', expectation: 'format' },
    { label: 'Panama RUC personale', country: 'PA', value: '8-340-1234', expectation: 'format' },
    { label: 'Micronesia Social Security Number', country: 'FM', value: '12-345678', expectation: 'format' },
    { label: 'Sudan National ID', country: 'SD', value: 'AB-123456', expectation: 'format' },
    { label: 'Zimbabwe TIN', country: 'ZW', value: '1234567890', expectation: 'format' },
    { label: 'Ciad NIF alfanumerico', country: 'TD', value: 'ABC12345', expectation: 'format' },
    { label: 'Comore NIF numerico', country: 'KM', value: '8301149211', expectation: 'format' },
    { label: 'Gibuti NIF alfanumerico', country: 'DJ', value: 'AB12345', expectation: 'format' },
    { label: 'Guinea Equatoriale NIF', country: 'GQ', value: 'A0704885T', expectation: 'format' },
    { label: 'Eritrea TIN alfanumerico', country: 'ER', value: '1234567', expectation: 'format' },
    { label: 'Gambia TIN numerico', country: 'GM', value: '1234567890', expectation: 'format' },
    { label: 'Niger NIF numerico', country: 'NE', value: '12345678', expectation: 'format' },
    { label: 'Somalia TIN numerico', country: 'SO', value: '12345678', expectation: 'format' },
    { label: 'Turkmenistan HSB', country: 'TM', value: '123456789012', expectation: 'format' },
    { label: 'Yemen raqm daribiy', country: 'YE', value: '123456789', expectation: 'format' },
    { label: 'Kiribati TIN alfanumerico', country: 'KI', value: '1234567', expectation: 'format' },
    { label: 'Tonga TIN alfanumerico', country: 'TO', value: '1234567', expectation: 'format' },
    {
      label: 'Paese non supportato',
      country: 'XX',
      value: '123456789',
      expectation: 'unsupported_country',
    },
  ];

  protected readonly country = new FormControl('IT', { nonNullable: true });
  protected readonly taxId = new FormControl('', {
    nonNullable: true,
    validators: [Validators.required, taxIdValidator(() => this.country.value)],
  });

  private readonly revision = signal(0);
  protected readonly hasInteracted = signal(false);

  protected readonly result = computed<TaxIdValidationResult | null>(() => {
    this.revision();
    const value = this.taxId.value;
    return value ? validateTaxId(this.country.value, value) : null;
  });

  protected readonly normalizedPreview = computed(() => {
    this.revision();
    return this.result()?.normalizedValue ?? normalizeTaxId(this.taxId.value);
  });

  constructor() {
    this.country.valueChanges.subscribe(() => {
      this.taxId.updateValueAndValidity();
      this.bumpRevision();
    });

    this.taxId.valueChanges.subscribe(() => this.bumpRevision());
  }

  protected validate(): void {
    this.hasInteracted.set(true);
    this.taxId.markAsTouched();
    this.taxId.updateValueAndValidity();
    this.bumpRevision();
  }

  protected useTestCase(testCase: TestCase): void {
    this.country.setValue(testCase.country);
    this.taxId.setValue(testCase.value);
    this.validate();
  }

  protected clear(): void {
    this.taxId.reset('');
    this.hasInteracted.set(false);
    this.bumpRevision();
  }

  protected errorLabel(error?: string): string {
    const labels: Record<string, string> = {
      empty: 'Valore vuoto',
      invalid_length: 'Lunghezza non valida',
      invalid_format: 'Formato non valido',
      invalid_checksum: 'Carattere di controllo non valido',
      not_applicable: 'TIN personale non applicabile',
      unsupported_country: 'Paese non ancora supportato',
    };

    return error ? (labels[error] ?? error) : 'Nessun errore';
  }

  private bumpRevision(): void {
    this.revision.update((value) => value + 1);
  }
}
